language: python

python:
  - "2.6"
  - "2.7"

install:
    - sudo pip install cython

script: 
    - python setup.py install
    - nosetests
    - make clean && make cython && make all && make clean && sudo make install && sudo make uninstall
