language: python

python:
  - "2.6"
  - "2.7"

install:
    - sudo pip install cython

script: 
    - python setup.py install
    - nosetests
    - sudo make clean && make cython && make all && sudo make install && sudo make uninstall && sudo make clean
