language: python

os:
  - osx
  - linux

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
    - python setup.py install
    - sudo pip install cython
script: 
    - nosetests
    # Timeout returns 124, but we want it to timeout and return 0; hacky
    - timeout 15s python test/wavetest.py || true
    - rm temp.wav
    - sudo make clean && make python2 && sudo make install && sudo make uninstall && sudo make clean
